set(_CATKIN_CURRENT_PACKAGE "turtlebot_navigation")
set(turtlebot_navigation_MAINTAINER "OSRF <turtlebot@osrfoundation.org>")
set(turtlebot_navigation_DEPRECATED "")
set(turtlebot_navigation_VERSION "2.2.3")
set(turtlebot_navigation_BUILD_DEPENDS "tf" "roscpp" "sensor_msgs" "base_local_planner" "clear_costmap_recovery" "navfn" "rotate_recovery")
set(turtlebot_navigation_RUN_DEPENDS "tf" "roscpp" "sensor_msgs" "move_base" "map_server" "amcl" "gmapping" "turtlebot_bringup" "base_local_planner" "clear_costmap_recovery" "rotate_recovery" "navfn")
set(turtlebot_navigation_BUILDTOOL_DEPENDS "catkin")